---
- name: K8s Kafka Event
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: automation-streams-kafka-bootstrap.skylight.svc.cluster.local
        port: 9092
        topic: kafka-test-topic
        group_id: ansible-eda

  rules:
    - name: kafka
      condition:
        all:
          - request.type is defined and request.type != ""
      action:
        run_job_template:
          name: Test-Template
          organization: Default


