- name: Get Cluster Info
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ns: 'skylight'

  tasks:
    - name: Get a list of all Pods in NS
      kubernetes.core.k8s_info:
        api_key: "AAP Service Account"
        validate_certs: no
        kind: Pod
        namespace: "{{ ns }}"
      register: pod_list