- name: Get Cluster Info
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - debug:
        msg: 'Retreiving Pod List for: {{ ansible_eda.event.body.namespace }}'

    - name: Get a list of all Pods in NS
      kubernetes.core.k8s_info:
        validate_certs: no
        kind: Pod
        namespace: "{{ ansible_eda.event.body.namespace }}"
      register: pod_list

    - debug:
        msg: "{{ item.metadata.name }} {{ item.metadata.namespace }}"
      loop: "{{ pod_list.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
