- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set resource quotas
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ ansible_eda.event.body.namespace.name }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"
