- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: no
  vars:
    ns: 'test'
    requests_cpu: '2'
    limits_cpu: '3'
    requests_memory: '5Gi'
    limits_memory: '10Gi'

  tasks:
    - name: Set resource quotas
      kubernetes.core.k8s:
        kubeconfig: "/opt/cedar/conf/auth/kubeconfig"
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ ns }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              "limits.cpu": "{{ limits_cpu }}"
              "limits.memory": "{{ limits_memory }}"
              "requests.cpu": "{{ requests_cpu }}"
              "requests.memory": "{{ requests_memory }}"
      delegate_to: ignite.demolab.local
